name: bumblebee
description: A client for the Pollen pubsub / streaming server.
version: 0.3.0
repository: https://github.com/EverestHC-mySofie/bumblebee

environment:
  sdk: ^3.5.2

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
